package com.tyvon.iron;

import android.app.*;import android.os.*;import android.content.*;import android.content.res.Configuration;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.text.InputType;import android.view.*;import android.widget.*;
import org.json.*;import java.util.*;import java.util.concurrent.*;import java.io.*;import java.text.*;

/** Native Android Views. No browser renderer or JavaScript bridge. */
public final class MainActivity extends Activity {
 static final int INK=Color.rgb(16,17,15),PANEL=Color.rgb(27,29,25),PAPER=Color.rgb(242,238,229),MUTED=Color.rgb(186,188,178),COPPER=Color.rgb(217,149,100),LINE=Color.rgb(54,58,50);
 final ExecutorService worker=Executors.newSingleThreadExecutor();final Handler handler=new Handler(Looper.getMainLooper());
 Vault vault;Api api;JSONObject state,user,profile,draft;JSONArray plan=new JSONArray();int revision=0;boolean busy=false,ready=false;String route="home",draftKey="";LinearLayout root,body,dock;TextView timer;long restUntil=0;
 interface Job{void run()throws Exception;}
 static JSONObject obj(Object... values){JSONObject j=new JSONObject();try{for(int i=0;i<values.length;i+=2)j.put(values[i].toString(),values[i+1]);}catch(Exception e){throw new IllegalArgumentException(e);}return j;}
 static JSONObject copy(JSONObject j){try{return new JSONObject(j.toString());}catch(Exception e){return new JSONObject();}}
 int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(INK);getWindow().setNavigationBarColor(INK);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);vault=new Vault(this);try{api=new Api(vault);}catch(Exception e){vault.remove("cookies");try{api=new Api(vault);}catch(Exception ex){error("Não foi possível abrir o armazenamento seguro.");return;}}loading();run(()->bootstrap(),()->render());handler.post(tick);}
 @Override public void onConfigurationChanged(Configuration c){super.onConfigurationChanged(c);render();}
 @Override public void onDestroy(){handler.removeCallbacksAndMessages(null);worker.shutdown();super.onDestroy();}
 final Runnable tick=new Runnable(){public void run(){if(timer!=null){long sec=Math.max(0,(restUntil-System.currentTimeMillis()+999)/1000);timer.setText(sec>0?String.format(Locale.US,"DESCANSO  %02d:%02d",sec/60,sec%60):"DESCANSO CONCLUÍDO");}handler.postDelayed(this,1000);}};
 void run(Job task,Runnable done){if(busy)return;busy=true;TextView progress=text("Conectando ao servidor…",14,COPPER);progress.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);progress.setPadding(dp(20),dp(8),dp(20),dp(8));if(root!=null)root.addView(progress,1);worker.execute(()->{try{task.run();runOnUiThread(()->{busy=false;if(progress.getParent() instanceof android.view.ViewGroup)((android.view.ViewGroup)progress.getParent()).removeView(progress);if(!isFinishing())done.run();});}catch(Exception e){runOnUiThread(()->{busy=false;if(progress.getParent() instanceof android.view.ViewGroup)((android.view.ViewGroup)progress.getParent()).removeView(progress);if(!isFinishing()){if(!ready)login(false);error(e.getMessage()==null?"Sem conexão. Tente novamente.":e.getMessage());}});}});}
 void bootstrap()throws Exception{
  try{JSONObject j=api.call("/api/native/v1/bootstrap","GET",null,null,null);user=j.getJSONObject("user");state=j.optJSONObject("state");revision=j.optInt("revision");plan=j.optJSONArray("plan");if(plan==null)plan=new JSONArray();profile=state==null?null:state.optJSONObject("profile");ready=true;draftKey="draft:"+user.getString("id");String local=vault.get(draftKey);draft=local.isEmpty()?null:new JSONObject(local);if(draft!=null)restUntil=draft.optLong("restUntil");}
  catch(Api.ApiError e){if(e.status==401){ready=false;user=null;state=null;profile=null;draft=null;return;}throw e;}
 }
 void save(JSONObject next)throws Exception{JSONObject j=api.call("/api/account",state==null?"POST":"PUT",next,state==null?null:revision,null);state=j.getJSONObject("state");revision=j.getInt("revision");profile=state.optJSONObject("profile");}
 void saveDraft()throws Exception{if(draft!=null)vault.put(draftKey,draft.toString());}
 void error(String s){new AlertDialog.Builder(this).setTitle("TYVON").setMessage(s).setPositiveButton("Entendi",null).show();}
 GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));d.setStroke(dp(1),LINE);return d;}
 LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(6),0,dp(6));t.setLineSpacing(dp(2),1);return t;}
 TextView title(String s){TextView t=text(s,32,PAPER);t.setTypeface(Typeface.create("sans-serif-condensed",Typeface.BOLD));return t;}
 void add(String s,int size,int color){body.addView(text(s,size,color));}
 Button button(String s,boolean primary,Runnable action){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(primary?INK:PAPER);b.setBackground(bg(primary?COPPER:PANEL,10));b.setMinHeight(dp(52));b.setPadding(dp(16),dp(8),dp(16),dp(8));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(12);b.setLayoutParams(p);b.setOnClickListener(v->{if(!busy)action.run();});return b;}
 void action(String s,boolean primary,Runnable r){body.addView(button(s,primary,r));}
 LinearLayout card(){LinearLayout l=column();l.setPadding(dp(18),dp(16),dp(18),dp(16));l.setBackground(bg(PANEL,16));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(16);l.setLayoutParams(p);body.addView(l);return l;}
 EditText field(LinearLayout parent,String label,String initial,int input){parent.addView(text(label,14,MUTED));EditText f=new EditText(this);f.setText(initial);f.setSingleLine(true);f.setTextSize(16);f.setTextColor(PAPER);f.setHintTextColor(MUTED);f.setInputType(input);f.setBackground(bg(PANEL,10));f.setPadding(dp(14),dp(10),dp(14),dp(10));f.setMinHeight(dp(52));parent.addView(f,new LinearLayout.LayoutParams(-1,-2));return f;}
 Spinner choose(LinearLayout parent,String label,String[] values,String selected){parent.addView(text(label,14,MUTED));Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,values);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(a);s.setMinimumHeight(dp(52));for(int i=0;i<values.length;i++)if(values[i].equals(selected))s.setSelection(i);parent.addView(s,new LinearLayout.LayoutParams(-1,-2));return s;}
 void shell(boolean navigation){timer=null;root=column();root.setBackgroundColor(INK);root.setFitsSystemWindows(false);root.setOnApplyWindowInsetsListener((v,insets)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());android.graphics.Insets keyboard=insets.getInsets(WindowInsets.Type.ime());v.setPadding(bars.left,bars.top,bars.right,Math.max(bars.bottom,keyboard.bottom));}else v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});setContentView(root);root.requestApplyInsets();LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(20),dp(10),dp(20),dp(10));ImageView mark=new ImageView(this);mark.setImageResource(com.tyvon.iron.R.drawable.mark);mark.setContentDescription("TYVON, símbolo de supino");header.addView(mark,new LinearLayout.LayoutParams(dp(40),dp(40)));TextView word=text("  TYVON",24,PAPER);word.setTypeface(Typeface.DEFAULT,Typeface.BOLD);header.addView(word);root.addView(header);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=column();body.setPadding(dp(20),dp(8),dp(20),dp(24));FrameLayout center=new FrameLayout(this);center.addView(body,new FrameLayout.LayoutParams(Math.min(getResources().getDisplayMetrics().widthPixels,dp(720)),-2,Gravity.TOP|Gravity.CENTER_HORIZONTAL));scroll.addView(center);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));if(navigation){dock=new LinearLayout(this);dock.setPadding(dp(8),dp(8),dp(8),dp(8));dock.setBackgroundColor(PANEL);String[] ids={"home","plan","history","chat","profile"},labels={"Início","Ficha","Evolução","Treinador","Perfil"};for(int i=0;i<ids.length;i++){String id=ids[i];TextView b=text(labels[i],11,route.equals(id)?COPPER:MUTED);b.setGravity(Gravity.CENTER);b.setMinHeight(dp(52));b.setFocusable(true);b.setContentDescription(labels[i]);b.setOnClickListener(v->{if(!busy){route=id;render();}});dock.addView(b,new LinearLayout.LayoutParams(0,-2,1));}root.addView(dock);}}
 void loading(){shell(false);body.addView(title("Cada série conta."));add("Conectando ao TYVON…",16,MUTED);}
 void render(){if(!ready){login(false);return;}if(profile==null||!profile.optBoolean("complete")){onboarding();return;}if(route.equals("session")&&draft!=null){session();return;}shell(true);switch(route){case "plan":plans();break;case "history":history();break;case "chat":chat();break;case "profile":profilePage();break;default:home();}}
 void login(boolean register){shell(false);body.addView(title(register?"Seu caderno começa aqui.":"Seu treino. Seu progresso."));add("Bodybuilding / Iron Edition",14,COPPER);add("Entre na sua conta para carregar as fichas e os registros reais.",16,MUTED);EditText email=field(body,"E-mail","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);EditText password=field(body,"Senha — mínimo 10 caracteres","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);CheckBox accept=new CheckBox(this);accept.setText("Tenho 14 anos ou mais e aceito os Termos e a Política de Privacidade.");accept.setTextColor(MUTED);accept.setMinHeight(dp(48));if(register)body.addView(accept);action(register?"Criar conta":"Entrar",true,()->{String mail=email.getText().toString().trim(),pass=password.getText().toString();if(pass.length()<10||pass.length()>128||!mail.contains("@")){error("Informe um e-mail e uma senha válida de 10 a 128 caracteres.");return;}if(register&&!accept.isChecked()){error("Confirme a idade mínima e a aceitação dos termos.");return;}run(()->{api.call("/api/auth/"+(register?"register":"login"),"POST",obj("email",mail,"password",pass,"accepted",accept.isChecked()),null,null);bootstrap();},()->render());});action(register?"Já tenho conta":"Criar minha conta",false,()->login(!register));action("Esqueci minha senha",false,()->open("/?view=forgot"));action("Google / acessar a versão web",false,()->open("/"));action("Termos e privacidade",false,()->open("/privacidade"));add("O login Google abre a versão web. Ele ainda não conecta uma sessão a este cliente nativo.",14,MUTED);}
 void open(String path){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(Api.BASE+path)));}
 void onboarding(){shell(false);body.addView(title("Monte sua rotina."));add("A ficha considera sua experiência e equipamentos. Peso e altura são opcionais.",16,MUTED);JSONObject p=profile==null?new JSONObject():profile;
 EditText name=field(body,"Como te chamamos?",p.optString("name",""),InputType.TYPE_CLASS_TEXT);EditText age=field(body,"Idade (14–100)",p.has("age")?p.optString("age",""):"",InputType.TYPE_CLASS_NUMBER);
 Spinner goal=choose(body,"Objetivo",new String[]{"Ganhar massa muscular","Criar uma rotina","Melhorar condicionamento","Perder gordura"},p.optString("goal"));Spinner level=choose(body,"Experiência",new String[]{"Iniciante","Intermediário","Avançado"},p.optString("experience"));Spinner days=choose(body,"Dias na semana",new String[]{"2","3","4","5"},p.optString("days","3"));Spinner minutes=choose(body,"Tempo por sessão",new String[]{"30","45","60","75","90"},p.optString("sessionMinutes","60"));EditText weight=field(body,"Peso em kg — opcional",p.isNull("weight")?"":p.optString("weight",""),InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText height=field(body,"Altura em cm — opcional",p.isNull("height")?"":p.optString("height",""),InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);
 add("Equipamentos disponíveis",18,PAPER);List<CheckBox> equipments=new ArrayList<>();for(String e:new String[]{"Halteres","Barras","Máquinas","Cabos","Banco","Peso corporal"}){CheckBox cb=new CheckBox(this);cb.setText(e);cb.setTextColor(PAPER);cb.setMinHeight(dp(48));cb.setChecked(p.optJSONArray("equipment")!=null&&p.optJSONArray("equipment").toString().contains('"'+e+'"'));equipments.add(cb);body.addView(cb);}
 EditText limitations=field(body,"Restrições — escreva Nenhuma se não houver",p.optString("limitations","Nenhuma"),InputType.TYPE_CLASS_TEXT);CheckBox sensitive=new CheckBox(this);sensitive.setText("Autorizo usar a restrição informada para personalização e alertas.");sensitive.setTextColor(MUTED);sensitive.setMinHeight(dp(48));body.addView(sensitive);add("Uma restrição não é convertida automaticamente em reabilitação. Valide sua ficha com um profissional.",14,MUTED);
 action("Salvar e abrir minha ficha",true,()->{try{int n=Integer.parseInt(age.getText().toString());if(n<14||n>100)throw new Exception("Informe uma idade de 14 a 100 anos.");JSONArray eq=new JSONArray();for(CheckBox c:equipments)if(c.isChecked())eq.put(c.getText());if(eq.length()==0)throw new Exception("Escolha os equipamentos disponíveis.");String restriction=limitations.getText().toString().trim();if(!restriction.isEmpty()&&!restriction.equals("Nenhuma")&&!sensitive.isChecked())throw new Exception("Autorize o uso da restrição ou remova esse dado.");JSONObject np=obj("name",name.getText().toString(),"age",n,"goal",goal.getSelectedItem(),"experience",level.getSelectedItem(),"days",Integer.parseInt(days.getSelectedItem().toString()),"sessionMinutes",Integer.parseInt(minutes.getSelectedItem().toString()),"weight",numberOptional(weight),"height",numberOptional(height),"equipment",eq,"limitations",restriction,"complete",true);JSONObject next=state==null?obj("profile",np,"logs",new JSONArray(),"messages",new JSONArray(),"step",0):copy(state);next.put("profile",np);run(()->{save(next);bootstrap();},()->{route="home";render();});}catch(Exception e){error(e.getMessage());}});if(profile!=null&&profile.optBoolean("complete"))action("Cancelar",false,()->{route="profile";render();});}
 Object numberOptional(EditText e)throws Exception{String s=e.getText().toString().trim();if(s.isEmpty())return JSONObject.NULL;double d=Double.parseDouble(s.replace(',','.'));if(!Double.isFinite(d))throw new Exception("Número inválido.");return d;}
 JSONArray logs(){JSONArray l=state==null?null:state.optJSONArray("logs");return l==null?new JSONArray():l;}
 int nextIndex(){JSONArray l=logs();if(l.length()==0||plan.length()==0)return 0;JSONObject last=l.optJSONObject(l.length()-1);int id=0;String lastName=last.optString("name").replace(" · parcial","");for(int i=0;i<plan.length();i++)if(plan.optJSONObject(i).optString("name").equals(lastName)){id=i;break;}return Math.floorMod(id+(last.optJSONObject("feedback")!=null&&last.optJSONObject("feedback").optBoolean("partial")?0:1),plan.length());}
 void home(){add("IRON / SEU CADERNO",13,COPPER);body.addView(title("Vamos ao treino, "+profile.optString("name","Atleta").split(" ")[0]+"."));if(draft!=null){LinearLayout c=card();c.addView(text("TREINO EM ANDAMENTO",13,COPPER));c.addView(text(draft.optJSONObject("workout").optString("name"),22,PAPER));c.addView(button("Continuar de onde parei",true,()->{route="session";render();}));}if(plan.length()>0){JSONObject w=plan.optJSONObject(nextIndex());workoutCard(w,true);}add(logs().length()+" sessões registradas",18,PAPER);add(profile.optString("goal")+" · "+profile.optString("experience"),16,MUTED);action("Atualizar dados do servidor",false,()->run(()->bootstrap(),()->render()));}
 void workoutCard(JSONObject w,boolean primary){LinearLayout c=card();c.addView(text("FICHA "+(char)('A'+w.optInt("id")),13,COPPER));c.addView(text(w.optString("name"),26,PAPER));c.addView(text(w.optString("focus"),16,MUTED));JSONArray ex=w.optJSONArray("exercises");c.addView(text((ex==null?0:ex.length())+" exercícios · "+w.optInt("minutes")+" min estimados",14,MUTED));c.addView(button("Começar treino",primary,()->start(w)));}
 void plans(){body.addView(title("Suas fichas."));add("Construídas pelo motor TYVON com seu perfil salvo.",16,MUTED);for(int i=0;i<plan.length();i++)workoutCard(plan.optJSONObject(i),i==nextIndex());}
 void start(JSONObject workout){if(draft!=null){new AlertDialog.Builder(this).setTitle("Seu treino está em andamento").setMessage("Continue ou conclua a sessão atual antes de iniciar outra ficha.").setPositiveButton("Continuar",(d,w)->{route="session";render();}).setNegativeButton("Voltar",null).show();return;}if(!profile.optString("limitations","Nenhuma").equals("Nenhuma")){new AlertDialog.Builder(this).setTitle("Valide a ficha").setMessage("Você informou uma restrição. O motor não adapta exercícios clinicamente. Confirme que a ficha foi validada por um profissional antes de executar.").setPositiveButton("Ficha validada",(d,w)->createDraft(workout)).setNegativeButton("Voltar",null).show();}else createDraft(workout);}
 void createDraft(JSONObject w){draft=obj("id",UUID.randomUUID().toString(),"workout",w,"startedAt",System.currentTimeMillis(),"setLogs",new JSONArray(),"restUntil",0);try{saveDraft();route="session";render();}catch(Exception e){draft=null;error(e.getMessage());}}
 boolean completed(String id,int index){JSONArray sets=draft.optJSONArray("setLogs");for(int i=0;i<sets.length();i++){JSONObject s=sets.optJSONObject(i);if(s.optString("exerciseId").equals(id)&&s.optInt("setIndex")==index)return true;}return false;}
 JSONObject lastSet(JSONObject exercise){JSONArray l=logs();for(int i=l.length()-1;i>=0;i--){JSONArray s=l.optJSONObject(i).optJSONArray("setLogs");if(s==null)continue;for(int k=s.length()-1;k>=0;k--){JSONObject item=s.optJSONObject(k);if(item.optString("exerciseId").equals(exercise.optString("id")))return item;}}return null;}
 void session(){shell(false);JSONObject w=draft.optJSONObject("workout");add("FICHA "+(char)('A'+w.optInt("id"))+" / SESSÃO",13,COPPER);body.addView(title(w.optString("name")));timer=text("",22,COPPER);timer.setTypeface(Typeface.MONOSPACE);body.addView(timer);action("Encerrar descanso",false,()->{restUntil=0;try{draft.put("restUntil",0);saveDraft();}catch(Exception e){error(e.getMessage());}});add(w.optString("note"),14,MUTED);JSONArray exercises=w.optJSONArray("exercises");for(int i=0;i<exercises.length();i++){JSONObject e=exercises.optJSONObject(i);LinearLayout c=card();c.addView(text(String.format(Locale.US,"%02d / %s",i+1,e.optString("group")),13,COPPER));c.addView(text(e.optString("name"),24,PAPER));c.addView(text(e.optInt("sets")+" × "+e.optString("reps")+" · RIR "+e.optInt("targetRir")+" · "+e.optInt("restSeconds")+" s de descanso",15,MUTED));c.addView(text("Aquecimento sugerido: "+e.optInt("warmupSets")+" séries · "+e.optString("tip"),14,MUTED));JSONObject previous=lastSet(e);if(previous!=null)c.addView(text("Último registro: "+previous.optDouble("weight")+" kg × "+previous.optInt("reps")+(e.optString("id").equals("plank")?" s":" reps"),14,COPPER));for(int si=1;si<=e.optInt("sets");si++){final int index=si;boolean done=completed(e.optString("id"),si);c.addView(button((done?"✓ ":"")+"Série "+si+(done?" — editar":" — registrar"),!done,()->record(e,index)));}}
 action("Concluir treino",true,()->confirmFinish());action("Voltar ao início — manter rascunho",false,()->{route="home";render();});}
 void record(JSONObject e,int index){LinearLayout form=column();form.setPadding(dp(24),dp(12),dp(24),dp(12));JSONObject old=null;JSONArray sets=draft.optJSONArray("setLogs");for(int i=0;i<sets.length();i++){JSONObject s=sets.optJSONObject(i);if(s.optString("exerciseId").equals(e.optString("id"))&&s.optInt("setIndex")==index)old=s;}boolean seconds=e.optString("id").equals("plank");EditText load=field(form,"Carga (kg) — 0 para peso corporal",old==null?"":old.optString("weight"),InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText reps=field(form,seconds?"Tempo (segundos)":"Repetições",old==null?"":old.optString("reps"),InputType.TYPE_CLASS_NUMBER);EditText rir=field(form,"RIR real (0–5) — opcional",old==null||old.isNull("rir")?"":old.optString("rir"),InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);ScrollView sc=new ScrollView(this);sc.addView(form);AlertDialog d=new AlertDialog.Builder(this).setTitle(e.optString("name")+" · série "+index).setView(sc).setPositiveButton("Registrar",null).setNegativeButton("Cancelar",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{try{double weight=Double.parseDouble(load.getText().toString().isEmpty()?"0":load.getText().toString().replace(',','.'));int r=Integer.parseInt(reps.getText().toString());Object effort=numberOptional(rir);if(weight<0||weight>500||r<1||r>(seconds?600:100)||effort!=JSONObject.NULL&&((Double)effort<0||(Double)effort>5))throw new Exception("Verifique carga, repetições e RIR.");JSONObject set=obj("exerciseId",e.optString("id"),"exerciseName",e.optString("name"),"group",e.optString("group"),"setIndex",index,"weight",weight,"reps",r,"rir",effort,"targetRir",e.optInt("targetRir"),"unit",seconds?"seconds":"reps","completed",true);JSONArray updated=new JSONArray();for(int i=0;i<sets.length();i++){JSONObject s=sets.optJSONObject(i);if(!(s.optString("exerciseId").equals(e.optString("id"))&&s.optInt("setIndex")==index))updated.put(s);}updated.put(set);JSONObject next=copy(draft);long deadline=System.currentTimeMillis()+e.optInt("restSeconds")*1000L;next.put("setLogs",updated);next.put("restUntil",deadline);vault.put(draftKey,next.toString());draft=next;restUntil=deadline;d.dismiss();session();}catch(Exception ex){error(ex.getMessage());}}));d.show();}
 void confirmFinish(){JSONArray sets=draft.optJSONArray("setLogs");if(sets.length()==0){error("Registre ao menos uma série antes de concluir.");return;}new AlertDialog.Builder(this).setTitle("Concluir sessão?").setMessage(sets.length()+" séries registradas. A confirmação aparece depois que o servidor salvar.").setPositiveButton("Salvar treino",(d,w)->finishWorkout()).setNegativeButton("Continuar",null).show();}
 void finishWorkout(){JSONObject pending=copy(draft);run(()->{JSONObject w=pending.getJSONObject("workout");JSONArray sets=pending.getJSONArray("setLogs");int planned=0;JSONArray es=w.getJSONArray("exercises");for(int i=0;i<es.length();i++)planned+=es.getJSONObject(i).optInt("sets");int minutes=Math.max(1,(int)((System.currentTimeMillis()-pending.getLong("startedAt"))/60000));JSONObject record=obj("id",pending.getString("id"),"date",new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.US).format(new Date(pending.getLong("startedAt"))),"name",w.getString("name"),"workoutId",w.getInt("id"),"minutes",minutes,"sets",sets.length(),"weights",new JSONObject(),"setLogs",sets,"feedback",obj("partial",sets.length()<planned),"engine","tyvon");JSONObject next=copy(state);JSONArray all=next.optJSONArray("logs");JSONArray merged=new JSONArray();for(int i=0;i<all.length();i++){JSONObject l=all.getJSONObject(i);if(!l.optString("id").equals(record.getString("id")))merged.put(l);}merged.put(record);next.put("logs",merged);save(next);vault.remove(draftKey);draft=null;restUntil=0;},()->{route="history";render();error("Treino salvo no servidor.");});}
 void history(){body.addView(title("Seu progresso real."));JSONArray l=logs();add(l.length()+" sessões registradas",18,COPPER);if(l.length()==0)add("Conclua sua primeira sessão para começar seu histórico.",16,MUTED);for(int i=l.length()-1;i>=0;i--){JSONObject log=l.optJSONObject(i);LinearLayout c=card();c.addView(text(log.optString("name"),24,PAPER));c.addView(text(log.optString("date").split("T")[0]+" · "+log.optInt("sets")+" séries · "+log.optInt("minutes")+" min",14,MUTED));JSONArray sets=log.optJSONArray("setLogs");if(sets!=null)for(int k=0;k<sets.length();k++){JSONObject s=sets.optJSONObject(k);c.addView(text(s.optString("exerciseName")+" · "+s.optDouble("weight")+" kg × "+s.optInt("reps")+(s.optString("unit").equals("seconds")?" s":" reps"),14,MUTED));}c.addView(button("Compartilhar resumo",false,()->share(log)));}}
 void share(JSONObject log){try{Bitmap image=Bitmap.createBitmap(1080,1350,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(image);c.drawColor(INK);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(COPPER);c.drawRect(64,64,1016,72,p);p.setTypeface(Typeface.create("sans-serif-condensed",Typeface.BOLD));p.setTextSize(88);p.setColor(PAPER);c.drawText("TYVON",64,210,p);p.setTextSize(34);p.setColor(COPPER);c.drawText("CADA SÉRIE CONTA.",64,285,p);p.setColor(PAPER);p.setTextSize(60);String name=log.optString("name");if(name.length()>28)name=name.substring(0,28)+"…";c.drawText(name,64,450,p);p.setTextSize(42);c.drawText(log.optInt("sets")+" SÉRIES  /  "+log.optInt("minutes")+" MIN",64,560,p);p.setColor(MUTED);p.setTextSize(30);c.drawText(log.optString("date").split("T")[0],64,635,p);JSONArray sets=log.optJSONArray("setLogs");Set<String> names=new LinkedHashSet<>();if(sets!=null)for(int i=0;i<sets.length();i++)names.add(sets.optJSONObject(i).optString("exerciseName"));int y=760;for(String e:names){if(y>1080)break;if(e.length()>42)e=e.substring(0,42)+"…";c.drawText(e,64,y,p);y+=64;}p.setColor(COPPER);c.drawRect(64,1190,1016,1194,p);p.setColor(PAPER);c.drawText("SEU TREINO. SEUS DADOS. SEU PROGRESSO.",64,1270,p);try(FileOutputStream out=new FileOutputStream(new File(getCacheDir(),"session.png"))){image.compress(Bitmap.CompressFormat.PNG,100,out);}image.recycle();Uri uri=Uri.parse("content://com.tyvon.iron.share/session.png");Intent intent=new Intent(Intent.ACTION_SEND);intent.setType("image/png");intent.putExtra(Intent.EXTRA_STREAM,uri);intent.setClipData(ClipData.newRawUri("Resumo TYVON",uri));intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(intent,"Compartilhar seu treino"));}catch(Exception e){error("Não foi possível gerar o resumo.");}}
 void chat(){body.addView(title("Seu treinador."));add("Pergunte sobre técnica e rotina. A ficha vem do motor TYVON; respostas gerais usam IA.",14,MUTED);JSONArray messages=state.optJSONArray("messages");if(messages!=null)for(int i=Math.max(0,messages.length()-12);i<messages.length();i++){JSONObject m=messages.optJSONObject(i);LinearLayout c=card();c.addView(text(m.optString("role").equals("user")?"VOCÊ":"TYVON",12,COPPER));c.addView(text(m.optString("text"),16,PAPER));}EditText input=field(body,"Sua pergunta","",InputType.TYPE_CLASS_TEXT);input.setSingleLine(false);input.setMaxLines(5);action("Enviar",true,()->{String question=input.getText().toString().trim();if(question.isEmpty()||question.length()>5000){error("Escreva uma pergunta de até 5.000 caracteres.");return;}TextView answer=text("Pensando…",16,PAPER);body.addView(answer);run(()->{JSONArray history=new JSONArray();JSONArray previous=state.optJSONArray("messages");if(previous!=null)for(int i=Math.max(0,previous.length()-20);i<previous.length();i++){JSONObject m=previous.optJSONObject(i);history.put(obj("role",m.optString("role").equals("user")?"user":"assistant","content",m.optString("text")));}history.put(obj("role","user","content",question));StringBuilder reply=new StringBuilder();final String[] failure={null};api.call("/api/chat","POST",obj("messages",history,"nextWorkoutId",nextIndex()),null,event->{String type=event.optString("type");if(type.equals("token")){reply.append(event.optString("text"));runOnUiThread(()->answer.setText(reply.toString()));}else if(type.equals("error"))failure[0]=event.optString("error",event.optString("message","IA indisponível."));else if(type.equals("workouts")){reply.append("\nSua ficha está disponível na aba Ficha.");}});if(failure[0]!=null)throw new Exception(failure[0]);if(reply.length()==0)throw new Exception("O servidor não enviou uma resposta. Tente novamente.");JSONObject next=copy(state);JSONArray ms=next.optJSONArray("messages");if(ms==null)ms=new JSONArray();ms.put(obj("role","user","text",question));ms.put(obj("role","ai","text",reply.toString()));next.put("messages",ms);save(next);},()->render());});}
 void profilePage(){body.addView(title(profile.optString("name")));add(profile.optString("goal"),18,COPPER);add(profile.optString("experience")+" · "+profile.optInt("days")+" dias · "+profile.optInt("sessionMinutes")+" min",16,MUTED);add("Peso e altura são contexto. A carga é registrada por você; este cliente não inventa uma carga inicial.",14,MUTED);action("Ajustar perfil e equipamentos",false,()->onboarding());action("Atualizar / resolver dados de outro aparelho",false,()->run(()->bootstrap(),()->render()));action("Recuperação e segurança da conta (web)",false,()->open("/"));action("Termos e política de privacidade",false,()->open("/privacidade"));action("Solicitar exclusão dos meus dados",false,()->{new AlertDialog.Builder(this).setTitle("Solicitar exclusão").setMessage("Envia uma solicitação vinculada à sua conta. O servidor informa o protocolo; o pedido não apaga dados instantaneamente.").setPositiveButton("Solicitar",(d,w)->run(()->{JSONObject r=api.call("/api/privacy/requests","POST",obj("kind","deletion","email",user.optString("email"),"details","Exclusão solicitada pelo cliente Android TYVON Iron."),null,null);runOnUiThread(()->error("Solicitação registrada. Protocolo: "+r.optString("protocol")));},()->{})).setNegativeButton("Cancelar",null).show();});action("Sair da conta",false,()->run(()->{api.call("/api/auth/logout","POST",new JSONObject(),null,null);vault.remove("cookies");api.cookies.clear();draft=null;ready=false;profile=null;state=null;user=null;},()->render()));add("TYVON Iron 2.0 · cliente nativo de validação",14,MUTED);}
 @Override public void onBackPressed(){if(route.equals("session")&&draft!=null){new AlertDialog.Builder(this).setTitle("Manter seu treino?").setMessage("As séries ficam no rascunho deste aparelho.").setPositiveButton("Voltar ao início",(d,w)->{route="home";render();}).setNegativeButton("Continuar",null).show();}else if(ready&&!route.equals("home")){route="home";render();}else super.onBackPressed();}
}
