import React,{useMemo,useState} from 'react';
import {Activity,Clock,Dumbbell,TrendingUp,CalendarDays} from 'lucide-react';
import {buildExerciseHistory,buildConsistency} from './exercise-history.js';
import './exercise-history.css';

export default function AnalyticsPage({logs=[],go}){
 const [selectedKey,setSelectedKey]=useState('');
 const exerciseHistory=useMemo(()=>buildExerciseHistory(logs),[logs]);
 const consistency=useMemo(()=>buildConsistency(logs),[logs]);
 const selectedExercise=exerciseHistory.find(item=>item.key===selectedKey)||exerciseHistory[0];
 const stats=useMemo(()=>{const minutes=logs.reduce((a,l)=>a+Number(l.minutes||0),0),sets=logs.reduce((a,l)=>a+Number(l.sets||0),0);const cutoff=Date.now()-30*86400000,recent=logs.filter(l=>new Date(l.date).getTime()>=cutoff);return {minutes,sets,recent}},[logs]);
 const max=Math.max(1,...logs.slice(-8).map(l=>Number(l.sets||0)));
 return <div className="v1-page">
  <header className="v1-page-head"><div><span>MINHA EVOLUÇÃO</span><h1>Consistência que <em>fica visível.</em></h1><p>O TYVON mostra o que você registrou. Sem ranking corporal e sem comparação com outras pessoas.</p></div><TrendingUp size={30}/></header>
  <div className="v1-stats"><article><Dumbbell/><span>Treinos registrados</span><strong>{logs.length}</strong></article><article><Clock/><span>Tempo acumulado</span><strong>{Math.round(stats.minutes)} min</strong></article><article><Activity/><span>Séries concluídas</span><strong>{Math.round(stats.sets)}</strong></article><article><CalendarDays/><span>Últimos 30 dias</span><strong>{stats.recent.length}</strong></article></div>
  <section className="v1-history-card exercise-consistency"><div className="v1-section-title"><div><span>SEU RITMO</span><h2>{consistency.activeDays} dias de treino em 30 dias</h2><p>{consistency.sessions} sessões registradas. Cada dia conta uma vez para sua consistência.</p></div></div><div className="exercise-calendar" aria-label="Consistência dos últimos 30 dias">{consistency.days.map(day=><span key={day.key} className={day.count?'trained':''} title={`${new Date(day.date).toLocaleDateString('pt-BR')}: ${day.count} treinos`} aria-label={`${new Date(day.date).toLocaleDateString('pt-BR')}: ${day.count} treinos`}>{new Date(day.date).getDate()}</span>)}</div><p className="exercise-record-note">Os dias destacados têm pelo menos um treino salvo.</p></section>
  <section className="v1-history-card exercise-history"><div className="v1-section-title"><div><span>EXERCÍCIO POR EXERCÍCIO</span><h2>Veja o que você fez.</h2><p>Cargas e repetições das séries que você concluiu e salvou.</p></div></div>
   {selectedExercise?<><label className="exercise-picker" htmlFor="history-exercise">Escolha um exercício<select id="history-exercise" value={selectedExercise.key} onChange={event=>setSelectedKey(event.target.value)}>{exerciseHistory.map(item=><option key={item.key} value={item.key}>{item.name}</option>)}</select></label><div className="exercise-record-stats"><article><span>Último registro</span><strong>{new Date(selectedExercise.latestSets[0].date).toLocaleDateString('pt-BR')}</strong><small>{selectedExercise.latestSets.length} séries salvas</small></article><article><span>Maior carga registrada</span><strong>{selectedExercise.best?`${selectedExercise.best.weight.toLocaleString('pt-BR')} kg`:'Peso corporal'}</strong><small>{selectedExercise.best?`${selectedExercise.best.reps} reps em ${new Date(selectedExercise.best.date).toLocaleDateString('pt-BR')}`:'Sem carga externa registrada'}</small></article></div><h3 className="exercise-latest-title">Séries da última sessão</h3><div className="exercise-set-list">{selectedExercise.latestSets.map((set,index)=><div key={index}><span>Série {set.setIndex||index+1}</span><strong>{set.weight>0?`${set.weight.toLocaleString('pt-BR')} kg`:'Peso corporal'}</strong><b>{set.reps} reps</b></div>)}</div><p className="exercise-record-note">{selectedExercise.sessionCount} sessões com este exercício. A maior carga é um registro real; não é uma estimativa de força máxima. Exercícios por tempo, como prancha, não entram nesta comparação.</p></>:<div className="v1-empty"><Activity size={28}/><h3>A evolução aparece série por série.</h3><p>Salve séries com carga e repetições no seu próximo treino para acompanhar cada exercício. Treinos antigos sem esses detalhes continuam no histórico abaixo.</p><button className="v1-primary" onClick={()=>go('workouts')}>Abrir meus treinos</button></div>}
  </section>
  <section className="v1-history-card"><div className="v1-section-title"><div><span>ÚLTIMAS SESSÕES</span><h2>Seu histórico</h2></div></div>
   {logs.length?<><div className="v1-mini-chart">{logs.slice(-8).map(l=><i key={l.id} style={{height:Math.max(10,Number(l.sets||0)/max*100)+'%'}} title={l.name}/>)}</div><div className="v1-history-list">{logs.slice(-8).reverse().map(l=><div key={l.id}><span><strong>{l.name}</strong><small>{new Date(l.date).toLocaleDateString('pt-BR')}</small></span><b>{Math.round(Number(l.sets||0))} séries</b><b>{Math.round(Number(l.minutes||0))} min</b></div>)}</div></>:<div className="v1-empty"><Dumbbell size={28}/><h3>Seu histórico começa no primeiro treino.</h3><p>Quando você salvar uma sessão, ela aparece aqui.</p><button className="v1-primary" onClick={()=>go('workouts')}>Abrir meus treinos</button></div>}
  </section>
 </div>
}
