import React,{useEffect,useState} from 'react';
import {AnimatePresence,motion} from 'motion/react';
import {ChevronLeft,Eye,EyeOff,LoaderCircle,LockKeyhole,MessageCircle,ShieldCheck,UserRound} from 'lucide-react';
import Bot from './Bot';
import {steps} from './logic';
import {apiFetch} from './api.js';

export default function Entry({blocked=false,Logo,user,profile,loading,error,onRetry,onStart,onContinue,onImport,legacy,saveError,onSaveRetry,onAuthenticate,onSignOut,onDashboard}){
 const params=new URLSearchParams(location.search),resetToken=params.get('reset_token')||'';
 const [view,setView]=useState(resetToken?'reset':'welcome'),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 const [showPassword,setShowPassword]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[google,setGoogle]=useState(false),[recoveryMessage,setRecoveryMessage]=useState('');

 useEffect(()=>{fetch('/api/auth/status',{cache:'no-store'}).then(r=>r.json()).then(d=>setGoogle(d.google)).catch(()=>{});if(params.has('auth_error'))setFormError('Não foi possível entrar com Google. Tente novamente ou use e-mail e senha.');if(params.get('email_verified')==='1')setRecoveryMessage('E-mail confirmado. Sua conta está protegida.');if(params.get('email_verified')==='0')setFormError('Esse link de verificação expirou ou já foi usado.')},[]);

 function changeView(next){setView(next);setFormError('');setRecoveryMessage('');setPassword('');setConfirmPassword('');window.scrollTo({top:0,behavior:'instant'})}
 async function start(imported=false){setFormError('');setBusy(true);try{await(imported?onImport():onStart())}catch(e){setFormError(e.message)}finally{setBusy(false)}}
 async function authenticate(e){e.preventDefault();setBusy(true);setFormError('');try{await onAuthenticate(view,{email,password,accepted})}catch(e){setFormError(e.message)}finally{setBusy(false)}}
 async function forgot(e){
  e.preventDefault();setBusy(true);setFormError('');setRecoveryMessage('');
  try{const r=await apiFetch('/api/auth/forgot-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível solicitar a recuperação.');setRecoveryMessage(d.message||'Se esse e-mail estiver cadastrado, enviaremos as instruções.')}
  catch(e){setFormError(e.message)}finally{setBusy(false)}
 }
 async function reset(e){
  e.preventDefault();setFormError('');setRecoveryMessage('');
  if(password!==confirmPassword){setFormError('As senhas não coincidem.');return}
  setBusy(true);
  try{const r=await apiFetch('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:resetToken,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível redefinir a senha.');history.replaceState({},'',location.pathname);setRecoveryMessage('Senha redefinida. Agora entre com a nova senha.');setView('login');setPassword('');setConfirmPassword('')}
  catch(e){setFormError(e.message)}finally{setBusy(false)}
 }

 const hasProfile=!!profile,name=profile?.name?.split(' ')[0];
 const remaining=hasProfile&&!profile.complete?Math.max(0,steps.length-(profile.step||0))+' passos para deixar tudo pronto':'Uma pergunta por vez';
 const recoverLabel=legacy?'Recuperar perfil de '+legacy.name+' deste aparelho':'Recuperar perfil deste aparelho';
 return <div className="entry-shell" inert={blocked}><header className="entry-header"><Logo/><span>SEU RITMO. SEU TYVON.</span></header><div className="entry-layout"><div className="entry-brand-scene" aria-hidden="true"><img src="/gym.jpg" alt=""/><div className="entry-scene-shade"/><div className="entry-scene-copy"><span>TYVON / PERFORMANCE</span><p>A sua próxima<br/>versão começa<br/>com você.</p><div><span>01</span><span>UMA REPETIÇÃO DE CADA VEZ.</span></div></div></div><main className="entry-surface"><AnimatePresence mode="wait"><motion.div className={'entry-content entry-'+view} key={view} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.2}}>
 {view!=='welcome'&&view!=='reset'&&<button className="entry-back" onClick={()=>changeView(view==='forgot'?'login':'welcome')}><ChevronLeft size={18}/>Voltar</button>}
 <div className="entry-companion"><Bot interactive/><span className="auth-companion-note">{view==='welcome'?'':'Seu companheiro TYVON'}</span></div>
 <div className="entry-eyebrow"><span className="entry-brand-rule"/><span>TYVON INTELLIGENCE</span></div>

 {view==='welcome'?<><h1>{hasProfile?<>Bom ter você<br/>de volta{name?', '+name:''}.</>:<>Seu treino.<br/><span>Seu ritmo.</span></>}</h1><p className="entry-description">{hasProfile?(profile.complete?'Seu plano, seus treinos e a sua conversa estão aqui. Vamos continuar?':'Seu perfil está em construção. O TYVON continua de onde você parou.'):'Escolha sua rotina e veja sua ficha. Depois, comece o treino em um toque.'}</p><div className="entry-facts"><span><MessageCircle size={15}/>{remaining}</span><span><span className="entry-fact-dot"/>No seu ritmo</span></div><div className="entry-actions"><button className="entry-primary" disabled={loading||!!error} onClick={()=>hasProfile?onContinue():changeView('register')}>{loading?<><LoaderCircle className="spin" size={18}/>Preparando seu espaço…</>:hasProfile?(profile.complete?'Continuar com o TYVON':'Continuar meu perfil'):'Criar conta'}</button><button className="entry-secondary" disabled={loading||!!error} onClick={()=>hasProfile&&profile.complete?onDashboard():changeView('login')}>{hasProfile&&profile.complete?'Abrir meu painel':'Entrar'}</button></div></>
 :view==='forgot'?<><h1>Recupere<br/><span>seu acesso.</span></h1><p className="entry-description">Informe seu e-mail. Se existir uma conta com senha, enviaremos um link temporário.</p><form className="entry-auth-form" onSubmit={forgot}><label>E-mail<input required type="email" autoComplete="email" placeholder="voce@email.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="entry-primary" disabled={busy}>{busy?<><LoaderCircle className="spin" size={18}/>Enviando…</>:'Enviar link de recuperação'}</button><button type="button" className="entry-switch" onClick={()=>changeView('login')}>Voltar para entrar</button></form></>
 :view==='reset'?<><h1>Nova senha.<br/><span>Novo acesso.</span></h1><p className="entry-description">Crie uma senha com pelo menos 10 caracteres. O link só pode ser usado uma vez.</p><form className="entry-auth-form" onSubmit={reset}><label>Nova senha<div className="auth-password"><input required type={showPassword?'text':'password'} minLength={10} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={showPassword?'Ocultar senha':'Mostrar senha'} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label><label>Confirmar senha<input required type="password" minLength={10} maxLength={128} autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><button className="entry-primary" disabled={busy}>{busy?<><LoaderCircle className="spin" size={18}/>Salvando…</>:'Redefinir senha'}</button></form></>
 :<><h1>{view==='login'?<>Seu espaço.<br/>Seu <span>ritmo.</span></>:<>Vamos começar<br/>por <span>você.</span></>}</h1><p className="entry-description">{view==='login'?'Entre para retomar sua conversa, seus treinos e sua evolução.':'Responda algumas perguntas simples sobre sua rotina. Altura e peso são opcionais. Você confere sua ficha antes de começar.'}</p>
 {user?<><div className="entry-identity"><div className="entry-identity-icon"><UserRound size={22}/></div><div><strong>{user.name||'Sua conta TYVON'}</strong><span>{user.email}</span></div><ShieldCheck size={18}/></div><button className="entry-switch" onClick={async()=>{try{await onSignOut()}catch{setFormError('Não foi possível sair da conta. Tente novamente.')}}}>Usar outra conta</button>{view==='register'&&!hasProfile&&<><div className="entry-process"><span><i>1</i>Crie seu perfil</span><span><i>2</i>Escolha sua rotina</span><span><i>3</i>Conheça seu plano</span></div><label className="entry-consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Tenho 14 anos ou mais e li e aceito os <a href="/termos" target="_top">Termos de Uso</a> e a <a href="/privacidade" target="_top">Política de Privacidade</a>. Se tenho menos de 18, usarei o TYVON com acompanhamento de responsável e profissional.</span></label></>}
 <div className="entry-actions">{hasProfile?<button className="entry-primary" onClick={onContinue}>Continuar {profile.complete?'meu espaço':'meu perfil'}</button>:view==='register'?<button className="entry-primary" disabled={!accepted||busy} onClick={()=>start()}>{busy?<><LoaderCircle className="spin" size={18}/>Criando seu espaço…</>:'Personalizar meu treino'}</button>:<><p className="entry-no-profile">Sua conta está conectada. Falta só criar seu perfil TYVON.</p><button className="entry-primary" onClick={()=>setView('register')}>Criar meu perfil</button>{legacy&&<button className="entry-secondary" disabled={busy} onClick={()=>start(true)}>{busy?'Recuperando…':recoverLabel}</button>}</>}
 <button className="entry-switch" onClick={()=>changeView(view==='register'?'login':'register')}>{view==='register'?'Já tenho conta. Entrar':'Primeira vez no TYVON? Criar conta'}</button></div></>
 :<form className="entry-auth-form" onSubmit={authenticate}><label>E-mail<input required type="email" autoComplete="email" placeholder="voce@email.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<div className="auth-password"><input required type={showPassword?'text':'password'} minLength={10} maxLength={128} autoComplete={view==='register'?'new-password':'current-password'} placeholder="Pelo menos 10 caracteres" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={showPassword?'Ocultar senha':'Mostrar senha'} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label>{view==='register'&&<label className="entry-consent"><input required type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Tenho 14 anos ou mais e li e aceito os <a href="/termos" target="_top">Termos de Uso</a> e a <a href="/privacidade" target="_top">Política de Privacidade</a>. Se tenho menos de 18, usarei o TYVON com acompanhamento de responsável e profissional.</span></label>}<button className="entry-primary" disabled={busy||(view==='register'&&!accepted)}>{busy?<><LoaderCircle className="spin" size={18}/>Preparando seu espaço…</>:view==='register'?'Criar conta e personalizar':'Entrar no TYVON'}</button>{view==='login'&&<button type="button" className="entry-switch entry-forgot" onClick={()=>changeView('forgot')}><LockKeyhole size={14}/>Esqueci minha senha</button>}<div className="auth-divider"><span/>ou<span/></div>{google?<a className="entry-secondary google-login" href="/api/auth/google" target="_top"><span className="google-g">G</span>Continuar com Google</a>:<><button type="button" className="entry-secondary google-login" disabled><span className="google-g">G</span>Google · indisponível</button><p className="entry-auth-note">E-mail e senha continuam disponíveis.</p></>}<button type="button" className="entry-switch" onClick={()=>changeView(view==='register'?'login':'register')}>{view==='register'?'Já tem conta? Entrar':'Primeira vez? Criar conta'}</button></form>}
 </>}

 {recoveryMessage&&<div className="entry-success" role="status"><ShieldCheck size={16}/><span>{recoveryMessage}</span></div>}
 {saveError&&<div className="entry-error" role="alert"><span>Seu progresso ainda não foi salvo.</span><button onClick={onSaveRetry}>Tentar salvar novamente</button></div>}
 {(error||formError)&&<div className="entry-error" role="alert"><span>{formError||error}</span>{error&&<button onClick={onRetry}>Tentar novamente</button>}</div>}
 <div className="entry-assurance"><ShieldCheck size={14}/><span>Seu perfil e progresso salvos na sua conta.</span></div>
 </motion.div></AnimatePresence><div className="entry-surface-footer"><span>BUILT AROUND YOU</span><span className="entry-legal-links"><a href="/termos" target="_top">Termos</a><a href="/privacidade" target="_top">Privacidade</a><span>TYVON © 2026</span></span></div></main></div></div>;
}
