import React,{useState} from 'react';
import {Dumbbell,MessageSquare,ChartNoAxesCombined,Clock,Play,Check,SlidersHorizontal} from 'lucide-react';
import Bot from './Bot';

export default function Home({p,plan,logs,go,start,ask,nextWorkoutId=0,draft,onResume}){
 const [selected,setSelected]=useState(nextWorkoutId),w=plan[Math.min(selected,plan.length-1)],last=logs.at(-1);
 const now=new Date(),monday=new Date(now.getFullYear(),now.getMonth(),now.getDate());monday.setDate(monday.getDate()-((monday.getDay()+6)%7));
 const weekly=logs.filter(l=>new Date(l.date)>=monday&&new Date(l.date)<=now),goal=plan.length,totalMinutes=logs.reduce((n,l)=>n+Number(l.minutes||0),0),greeting=now.getHours()<12?'Bom dia':now.getHours()<18?'Boa tarde':'Boa noite';
 return <div className="tyvon-home tyvon-home-training-first">
 <header className="home-heading"><div><span className="home-eyebrow">SEU ESPAÇO TYVON</span><h1>{greeting}, <span>{p.name.split(' ')[0]}.</span></h1><p>Abra sua ficha. Faça a primeira série. O resto vem no seu ritmo.</p></div></header>

 {draft&&<section className="home-resume" aria-label="Retomar treino"><div><span className="home-eyebrow">SEU TREINO ESTÁ AQUI</span><strong>{draft.workout.name}</strong><p>{Object.values(draft.checked).filter(Boolean).length} séries registradas · continue de onde parou</p></div><button className="home-primary" onClick={onResume}><Play size={17} fill="currentColor"/>Continuar treino</button></section>}
 <div className="home-layout home-training-layout"><section className="home-next"><div className="home-section-label"><span>SEU PRÓXIMO TREINO</span><button onClick={()=>go('workouts')}>Ver meu plano</button></div><div className="home-session-tabs" role="tablist" aria-label="Escolher treino">{plan.map((item,i)=><button key={item.id} role="tab" aria-selected={selected===i} aria-controls="home-selected-workout" onClick={()=>setSelected(i)}>Treino {String.fromCharCode(65+i)}{i===nextWorkoutId&&<span className="home-next-dot" aria-label="Próximo na sua sequência"/>}</button>)}</div><div id="home-selected-workout" role="tabpanel" className="home-workout"><div className="home-workout-number" aria-hidden="true">{String.fromCharCode(65+w.id)}</div><div className="home-workout-copy"><span className="home-eyebrow">{p.age<18?'TÉCNICA SUPERVISIONADA':'FEITO PARA A SUA ROTINA'}</span><h2>{w.name}</h2><p>{w.focus}</p><div className="home-workout-meta"><span><Clock size={16}/>{w.minutes} min</span><span><Dumbbell size={16}/>{w.exercises.length} exercícios</span></div></div><button className="home-primary" onClick={()=>start(w)}><Play size={17} fill="currentColor"/>Começar treino {String.fromCharCode(65+w.id)}</button><p className="home-ready-note">Ficha pronta · sem esperar pelo chat</p><div className="home-exercise-preview">{w.exercises.slice(0,4).map((e,i)=><div key={e.id||e.name}><span>{String(i+1).padStart(2,'0')}</span><strong>{e.name}</strong><span>{e.sets} × {e.reps}</span></div>)}{w.exercises.length>4&&<p>+ {w.exercises.length-4} exercícios no treino</p>}</div><p className="home-recovery">{w.recovery}</p></div></section>
 <aside className="home-week home-week-summary"><span className="home-eyebrow">SUA SEMANA</span><h2>{weekly.length?`${weekly.length} ${weekly.length===1?'treino registrado':'treinos registrados'}`:'Um passo de cada vez.'}</h2><p>{weekly.length?'Cada sessão faz parte da sua história.':'Seu primeiro treino registrado vai aparecer aqui.'}</p><div className="home-week-bars" role="img" aria-label={`${weekly.length} treinos registrados; ${goal} sessões no plano`}>{Array.from({length:goal},(_,i)=><span key={i} className={i<weekly.length?'done':''}>{i<weekly.length?<Check size={17}/>:String(i+1).padStart(2,'0')}</span>)}</div><div className="home-routine-note"><span>SEU OBJETIVO</span><strong>{p.goal}</strong><p>{p.days} dias por semana · {p.experience}</p><button onClick={()=>go('profile')}><SlidersHorizontal size={15}/>Ajustar minha rotina</button></div><button className="home-secondary" onClick={()=>go('analytics')}><ChartNoAxesCombined size={18}/>Ver minha evolução</button></aside></div>
 <section className="home-conversation" aria-labelledby="home-conversation-title"><div className="home-conversation-heading"><Bot/><div><span className="home-eyebrow">TYVON INTELLIGENCE</span><h2 id="home-conversation-title">Precisa de uma mão?</h2><p>Tire dúvidas sobre carga, técnica ou sua rotina.</p></div></div><button className="home-chat-entry" aria-label="Abrir conversa com TYVON" onClick={()=>go('chat')}><span>Converse com o TYVON…</span><MessageSquare size={22}/></button><div className="home-chat-questions"><button onClick={()=>go('workouts')}>Ver minha ficha</button><button onClick={()=>ask('Como escolher a carga?')}>Escolher minha carga</button><button onClick={()=>ask('Como organizar meu descanso?')}>Organizar descanso</button></div></section>
 <nav className="home-shortcuts" aria-label="Acessos rápidos"><button onClick={()=>go('workouts')}><Dumbbell size={21}/><span><strong>Meus treinos</strong><small>{plan.length} fichas completas</small></span></button><button onClick={()=>go('analytics')}><ChartNoAxesCombined size={21}/><span><strong>Minha evolução</strong><small>Seus registros e constância</small></span></button><button onClick={()=>go('profile')}><SlidersHorizontal size={21}/><span><strong>Meu perfil</strong><small>Rotina e cards compartilháveis</small></span></button></nav>
 <section className="home-journey"><div><span className="home-eyebrow">SUA JORNADA</span><p>{last?`Último treino: ${last.name} · ${new Date(last.date).toLocaleDateString('pt-BR')}`:'Seu progresso começa quando você registra uma sessão.'}</p></div><div className="home-journey-numbers"><span><strong>{logs.length}</strong> treinos</span><span><strong>{Math.round(totalMinutes)}</strong> minutos</span></div></section>
 </div>
}
