import ExerciseGuide from './ExerciseGuide';
import React,{useState,useId} from 'react';
import {motion} from 'motion/react';
import {Dumbbell,Clock,Play,ChevronDown,Activity,Target,Check} from 'lucide-react';
export default function WorkoutCards({workouts,onStart,onOpen}){
 const [selected,setSelected]=useState(0);const id=useId();if(!workouts?.length)return null;const w=workouts[Math.min(selected,workouts.length-1)];const recovery=w.kind==='recovery';const count=w.exercises.reduce((sum,e)=>sum+e.sets,0);
 return <section className="workout-deck" aria-label="Treinos apresentados pelo TYVON"><div className="workout-deck-heading"><span><Dumbbell size={15}/>{workouts.length>1?'SEU PLANO EM CARDS':'SEU PRÓXIMO TREINO'}</span><span>{workouts.length>1?`${selected+1} / ${workouts.length}`:'FEITO PARA VOCÊ'}</span></div>
 {workouts.length>1&&<div className="workout-card-tabs" role="tablist" aria-label="Escolha seu treino">{workouts.map((item,i)=><button key={item.id} id={`${id}-tab-${i}`} role="tab" aria-selected={selected===i} aria-controls={`${id}-panel`} tabIndex={selected===i?0:-1} onClick={()=>setSelected(i)} onKeyDown={e=>{let next;if(e.key==='ArrowRight')next=(i+1)%workouts.length;if(e.key==='ArrowLeft')next=(i-1+workouts.length)%workouts.length;if(e.key==='Home')next=0;if(e.key==='End')next=workouts.length-1;if(next!==undefined){e.preventDefault();setSelected(next);document.getElementById(`${id}-tab-${next}`)?.focus()}}}>{item.kind==='recovery'?'Recuperação':`Treino ${String.fromCharCode(65+item.id)}`}</button>)}</div>}
 <motion.article key={w.id} initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.18}} className="workout-chat-card" id={`${id}-panel`} {...(workouts.length>1?{role:'tabpanel','aria-labelledby':`${id}-tab-${selected}`}:{'aria-label':w.name})}>
 <div className="workout-card-hero"><div className="workout-card-top"><span className="workout-card-letter">{recovery?<Activity size={25}/>:String.fromCharCode(65+w.id)}</span><span className="workout-card-method">{recovery?'RECOVERY / TYVON':'PERFORMANCE / TYVON'}</span></div><h3>{w.name}</h3><p>{w.focus}</p><div className="workout-card-metrics"><span><Clock size={14}/>{w.minutes} min</span><span><Dumbbell size={14}/>{w.exercises.length} exercícios</span><span><Target size={14}/>{count} {recovery?'etapas':'séries principais'}</span></div></div>
 <div className="workout-card-protocol"><span><Check size={13}/>{recovery?'Movimento leve':'Ficha completa'}</span><span>{w.intensity}</span></div>
 <div className="workout-card-exercises">{w.exercises.map((e,i)=><details className="workout-card-exercise" key={i}><summary><span className="workout-card-num">{String(i+1).padStart(2,'0')}</span><span className="workout-card-exercise-name"><strong>{e.name}</strong><span>{e.group} · {e.equipment}</span></span><span className="workout-card-prescription"><strong>{e.sets} × {e.reps}</strong><span>{e.targetRir!=null?'RIR '+e.targetRir+' · ':''}{e.restSeconds}s descanso</span></span><ChevronDown size={14}/></summary><div className="workout-card-exercise-detail"><ExerciseGuide exercise={e}/></div></details>)}</div>
 <div className="workout-card-footer"><p>{w.note}</p><div className="workout-card-actions"><button className="workout-card-start" onClick={()=>onStart(w)}><Play size={15} fill="currentColor"/>{recovery?'Começar sessão':'Começar treino'}</button><button className="workout-card-open" onClick={onOpen}>Ver meu plano</button></div></div>
 </motion.article><p className="workout-deck-caption">{w.recovery}</p></section>
}
